// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnpBCwqGV7cZTPgXWGgVPxy-hRA6qEJ-s',
    appId: '1:407092753061:web:274d68320d5d8d4aef134c',
    messagingSenderId: '407092753061',
    projectId: 'prompt-pro-9f9fd',
    authDomain: 'prompt-pro-9f9fd.firebaseapp.com',
    storageBucket: 'prompt-pro-9f9fd.firebasestorage.app',
    measurementId: 'G-ZHGCFNFRM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk3gug--foqD6TDTT1kxIwQl8GVY0LruA',
    appId: '1:407092753061:android:781ecbd6fdfde4ccef134c',
    messagingSenderId: '407092753061',
    projectId: 'prompt-pro-9f9fd',
    storageBucket: 'prompt-pro-9f9fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBptZ5ZrZ1MzOMpDOORZ40WY5XyoCCF-w0',
    appId: '1:407092753061:ios:7370f10fd6355acfef134c',
    messagingSenderId: '407092753061',
    projectId: 'prompt-pro-9f9fd',
    storageBucket: 'prompt-pro-9f9fd.firebasestorage.app',
    iosBundleId: 'com.example.promptApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBptZ5ZrZ1MzOMpDOORZ40WY5XyoCCF-w0',
    appId: '1:407092753061:ios:7370f10fd6355acfef134c',
    messagingSenderId: '407092753061',
    projectId: 'prompt-pro-9f9fd',
    storageBucket: 'prompt-pro-9f9fd.firebasestorage.app',
    iosBundleId: 'com.example.promptApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnpBCwqGV7cZTPgXWGgVPxy-hRA6qEJ-s',
    appId: '1:407092753061:web:cd8f80bb8488f517ef134c',
    messagingSenderId: '407092753061',
    projectId: 'prompt-pro-9f9fd',
    authDomain: 'prompt-pro-9f9fd.firebaseapp.com',
    storageBucket: 'prompt-pro-9f9fd.firebasestorage.app',
    measurementId: 'G-HDJE0MJE0D',
  );

}